name: update-file-list

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-file-list:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository content
      uses: actions/checkout@v3

    - name: Generate file list
      run: |
        find . -name '*.csv' | grep -v 'file_list.csv' > file_list.csv

    - name: Configure Git
      run: |
        git config --global user.email "themichaelfactor13@gmail.com"
        git config --global user.name "GitHub Actions Bot"

    - name: Check for changes
      run: |
        if git diff --quiet; then
          echo "No changes to commit";
        else
          git add file_list.csv;
          git commit -m "Update file list";
          git push;
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication
