name: update-file-list

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-file-list:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository content
      uses: actions/checkout@v3 # Use the latest v3 version of checkout action

    - name: Generate file list
      run: |
        find . -name '*.csv' | grep -v 'file_list.csv' > file_list.csv

    - name: Commit and push changes
      run: |
        git config --global user.email "themichaelfactor13@gmail.com"
        git config --global user.name "GitHub Actions"
        git add file_list.csv
        git commit -m "Update file list"
        git push origin main
